### ISSUE TITLE
Handling multiline logs

### ISSUE THREAD

**Issue by sergeyarl** [fluent-plugins-nursery/fluent-plugin-cloudwatch-logs#112]
Hi! 

How multiline logs should be handled ?

If I specify 

```
  format multiline
  format_firstline /(?<log>.+)/
```
I get the following error:
`
2018-06-21 08:07:05 +0000 [error]: config error file="./vi-lambda-monitor.conf" error_class=Fluent::ConfigError error="Invalid regexp '': No named captures"`

if I use simply 

` format /(?<log>.+)/`

I get only first line of a log record saved.

Thanks! 

Regards,
Sergey

**Comment by sergeyarl** [comment]
Finally it is working . I simply had to change it to

`format none`

without `format` parameter specified I received the following error

```

2018-06-21 13:43:31 +0000 [error]: #0 unexpected error error_class=JSON::ParserError error="751: unexpected token at '-06-21T13:42:25.516Z\tee818f31-7558-11e8-a91d-6941d3c7a16b\tmonitoring event: { version: '0',\n  id: '93dcff4f-febe-a4a8-7a4b-2341233d063a',\n  'detail-type': 'Scheduled Event',\n  source: 'aws.events',\n  account: '1111111111',\n  time: '2018-06-21T13:41:39Z',\n  region: 'us-east-1',\n  resources: [ 'arn:aws:events:us-east-1:1111111111:rule/app-monitoring-event' ],\n  detail: {} }\n'"
  2018-06-21 13:43:31 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/2.4.0/json/common.rb:156:in `parse'
  2018-06-21 13:43:31 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/2.4.0/json/common.rb:156:in `parse'
  2018-06-21 13:43:31 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/2.4.0/json/common.rb:335:in `load'
  2018-06-21 13:43:31 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-cloudwatch-logs-0.5.0/lib/fluent/plugin/in_cloudwatch_logs.rb:135:in `emit'
  2018-06-21 13:43:31 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-cloudwatch-logs-0.5.0/lib/fluent/plugin/in_cloudwatch_logs.rb:114:in `block (2 levels) in run'
  2018-06-21 13:43:31 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-cloudwatch-logs-0.5.0/lib/fluent/plugin/in_cloudwatch_logs.rb:113:in `each'
  2018-06-21 13:43:31 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-cloudwatch-logs-0.5.0/lib/fluent/plugin/in_cloudwatch_logs.rb:113:in `block in run'
  2018-06-21 13:43:31 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-cloudwatch-logs-0.5.0/lib/fluent/plugin/in_cloudwatch_logs.rb:110:in `each'
  2018-06-21 13:43:31 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-cloudwatch-logs-0.5.0/lib/fluent/plugin/in_cloudwatch_logs.rb:110:in `run'
  2018-06-21 13:43:31 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2018-06-21 13:43:31 +0000 [error]: #0 unexpected error error_class=JSON::ParserError error="751: unexpected token at '-06-21T13:42:25.516Z\tee818f31-7558-11e8-a91d-6941d3c7a16b\tmonitoring event: { version: '0',\n  id: '93dcff4f-febe-a4a8-7a4b-2341233d063a',\n  'detail-type': 'Scheduled Event',\n  source: 'aws.events',\n  account: '1111111111',\n  time: '2018-06-21T13:41:39Z',\n  region: 'us-east-1',\n  resources: [ 'arn:aws:events:us-east-1:1111111111:rule/app-monitoring-event' ],\n  detail: {} }\n'"

Anyway, it can be closed now.

Regards,
Sergey
```
