### ISSUE TITLE
Rate exceeded

### ISSUE THREAD

**Issue by sergeyarl** [fluent-plugins-nursery/fluent-plugin-cloudwatch-logs#114]
I get this error all the time. 
Also not sure if `Worker 0 finished unexpectedly with status 1` doesn't affect other logs. 

```

2018-06-21 16:25:50 +0000 [warn]: #0 thread exited by unexpected error plugin=Fluent::Plugin::CloudwatchLogsInput title=:in_cloudwatch_logs_runner error_class=Aws::CloudWatchLogs::Errors::ThrottlingException error="Rate exceeded"
2018-06-21 16:25:50 +0000 [error]: #0 unexpected error error_class=Aws::CloudWatchLogs::Errors::ThrottlingException error="Rate exceeded"
  2018-06-21 16:25:50 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.21.2/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
  2018-06-21 16:25:50 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.21.2/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
  2018-06-21 16:25:50 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.21.2/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
  2018-06-21 16:25:50 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.21.2/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
  2018-06-21 16:25:50 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.21.2/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
  2018-06-21 16:25:50 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.21.2/lib/seahorse/client/plugins/response_target.rb:23:in `call'
  2018-06-21 16:25:50 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.21.2/lib/seahorse/client/request.rb:70:in `send_request'
  2018-06-21 16:25:50 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-cloudwatchlogs-1.3.0/lib/aws-sdk-cloudwatchlogs/client.rb:1154:in `get_log_events'
  2018-06-21 16:25:50 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-cloudwatch-logs-0.5.0/lib/fluent/plugin/in_cloudwatch_logs.rb:146:in `get_events'
  2018-06-21 16:25:50 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-cloudwatch-logs-0.5.0/lib/fluent/plugin/in_cloudwatch_logs.rb:112:in `block in run'
  2018-06-21 16:25:50 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-cloudwatch-logs-0.5.0/lib/fluent/plugin/in_cloudwatch_logs.rb:110:in `each'
  2018-06-21 16:25:50 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-cloudwatch-logs-0.5.0/lib/fluent/plugin/in_cloudwatch_logs.rb:110:in `run'
  2018-06-21 16:25:50 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2018-06-21 16:25:50 +0000 [error]: #0 unexpected error error_class=Aws::CloudWatchLogs::Errors::ThrottlingException error="Rate exceeded"
  2018-06-21 16:25:50 +0000 [error]: #0 suppressed same stacktrace
2018-06-21 16:25:50 +0000 [info]: Worker 0 finished unexpectedly with status 1
```
Thanks. 

Regards,
Sergey

**Comment by dpgaspar** [comment]
I'm getting this one too. I already have a fix for it and will submit a PR

**Comment by dpgaspar** [comment]
Ok it's on PR #113

**Comment by sergeyarl** [comment]
@dpgaspar Hi! As I understand your PR has nothing to do with fixing `Rate exceeded` error. correct?

**Comment by arnitolog** [comment]
faced with the same issue. Is there any solution on how to avoid throttling from the AWS side?

**Comment by yuki24** [comment]
@arnitolog This is not a support forum for AWS and there's nothing we can do to change how rete limiting works in AWS. Please contact AWS support directly. 

To fix the original issue, it may be interesting to allocate extra buffer until rate-limiting goes away, and flush the buffer once it's gone.

**Comment by kladiv** [comment]
+1 still present in 0.7.6
