### ISSUE TITLE
validation errors detected: Value '' at 'logEvents.1.member.message' failed to satisfy constraint: Member must have length greater than or equal to 1

### ISSUE THREAD

**Issue by koooge** [fluent-plugins-nursery/fluent-plugin-cloudwatch-logs#140]
#### Problem
Hi, I encountered the following Exception.

```
#<Thread:0x000055f4e4c6af50@/usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-cloudwatch-logs-0.7.2/lib/fluent/plugin/out_cloudwatch_logs.rb:244 run> terminated with exception (report_on_exception is true):
/usr/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.46.0/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': 10 validation errors detected: Value '' at 'logEvents.1.member.message' failed to satisfy constraint: Member must have length greater than or equal to 1; Value '' at 'logEvents.4.member.message' failed to satisfy constraint: Member must have length greater than or equal to 1; Value '' at 'logEvents.5.member.message' failed to satisfy constraint: Member must have length greater than or equal to 1; Value '' at 'logEvents.7.member.message' failed to satisfy constraint: Member must have length greater than or equal to 1; Value '' at 'logEvents.17.member.message' failed to satisfy constraint: Member must have length greater than or equal to 1; Value '' at 'logEvents.18.member.message' failed to satisfy constraint: Member must have length greater than or equal to 1; Value '' at 'logEvents.20.member.message' failed to satisfy constraint: Member must have length greater than or equal to 1; Value '' at 'logEvents.23.member.message' failed to satisfy constraint: Member must have length greater than or equal to 1; Value '' at 'logEvents.26.member.message' failed to satisfy constraint: Member must have length greater than or equal to 1; Value '' at 'logEvents.29.member.message' failed to satisfy constraint: Member must have length greater than or equal to 1 (Aws::CloudWatchLogs::Errors::InvalidParameterException)
	from /usr/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.46.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
	from /usr/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.46.0/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
	from /usr/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.46.0/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
	from /usr/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.46.0/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
	from /usr/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.46.0/lib/seahorse/client/plugins/response_target.rb:23:in `call'
	from /usr/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.46.0/lib/seahorse/client/request.rb:70:in `send_request'
	from /usr/lib/ruby/gems/2.5.0/gems/aws-sdk-cloudwatchlogs-1.13.0/lib/aws-sdk-cloudwatchlogs/client.rb:1626:in `put_log_events'
	from /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-cloudwatch-logs-0.7.2/lib/fluent/plugin/out_cloudwatch_logs.rb:329:in `put_events'
	from /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-cloudwatch-logs-0.7.2/lib/fluent/plugin/out_cloudwatch_logs.rb:309:in `put_events_by_chunk'
	from /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-cloudwatch-logs-0.7.2/lib/fluent/plugin/out_cloudwatch_logs.rb:247:in `block (2 levels) in write'
2019-01-30 03:17:00 +0000 [warn]: #0 failed to flush the buffer. retry_time=11 next_retry_seconds=2019-01-30 03:35:22 +0000 chunk="580a4189ef8b19a24ab0209a56754b50" error_class=Aws::CloudWatchLogs::Errors::InvalidParameterException error="10 validation errors detected: Value '' at 'logEvents.1.member.message' failed to satisfy constraint: Member must have length greater than or equal to 1; Value '' at 'logEvents.4.member.message' failed to satisfy constraint: Member must have length greater than or equal to 1; Value '' at 'logEvents.5.member.message' failed to satisfy constraint: Member must have length greater than or equal to 1; Value '' at 'logEvents.7.member.message' failed to satisfy constraint: Member must have length greater than or equal to 1; Value '' at 'logEvents.17.member.message' failed to satisfy constraint: Member must have length greater than or equal to 1; Value '' at 'logEvents.18.member.message' failed to satisfy constraint: Member must have length greater than or equal to 1; Value '' at 'logEvents.20.member.message' failed to satisfy constraint: Member must have length greater than or equal to 1; Value '' at 'logEvents.23.member.message' failed to satisfy constraint: Member must have length greater than or equal to 1; Value '' at 'logEvents.26.member.message' failed to satisfy constraint: Member must have length greater than or equal to 1; Value '' at 'logEvents.29.member.message' failed to satisfy constraint: Member must have length greater than or equal to 1"
  2019-01-30 03:17:00 +0000 [warn]: #0 suppressed same stacktrace
```
...

#### Steps to replicate
```
  <match foo.*>
    @type cloudwatch_logs
    log_group_name "bar"
    log_stream_name "${tag}"
    auto_create_stream true
    message_keys log
    max_message_length 32768
    include_time_key true
    put_log_events_retry_wait 1s
    put_log_events_retry_limit 17
    put_log_events_disable_retry_limit false
    <buffer tag>
      @type memory
    </buffer>
  </match>
```

#### Expected Behavior or What you need to ask

...

#### Using Fluentd and CloudWatchLogs plugin versions

* OS version
fluent/fluentd image

* Bare Metal or within Docker or Kubernetes or others?
docker

* Fluentd v0.12 or v0.14/v1.0
  * paste result of ``fluentd --version`` or ``td-agent --version``
fluentd 1.3.2

* Dependent gem versions
  * paste boot log of fluentd or td-agent
  * paste result of ``fluent-gem list``, ``td-agent-gem list`` or your Gemfile.lock
fluent-plugin-cloudwatch-logs (0.7.2)

**Comment by pandeyrahulgwl** [comment]
Can anyone help me out with the configuration required to send docker container logs to cloudwatch... 
It is present in my local gem list, even though I am able to proceed.

**Comment by jburgess777** [comment]
I was seeing similar exceptions. They appear to be triggered whenever the "log" string for an event is empty. I worked around this by using a pattern to exclude empty messages:
```
  <filter device-management-firelens**>
    @type grep
    <exclude>
      key "log"
      pattern ^$
    </exclude>
  </filter>
```

**Comment by logbon72** [comment]
@jburgess777's suggestion fixed this for me also, specified the filter as the last filter before the cloudwatch plugin config. 

I think empty lines should be excluded automatically from input. I'd send a PR, but Ruby is not one of the languages I'm fluent in (no pun).

**Comment by cosmo0920** [comment]
I'd created a patch for fixing this.
Could you take a look, @koooge , @pandeyrahulgwl , @logbon72 .
And thank you for posting a workaround, @jburgess777 !
