### ISSUE TITLE
source sequence is illegal/malformed utf-8 (JSON::GeneratorError)

### ISSUE THREAD

**Issue by RootTJNII** [fluent-plugins-nursery/fluent-plugin-cloudwatch-logs#152]
#### Problem

fluent-plugin-cloudwatch-logs is crashing with the following error:

```
2019-05-30 03:40:39 +0000 [warn]: #0 failed to flush the buffer. retry_time=5 next_retry_seconds=2019-05-30 03:40:56 +0000 chunk="589eb6c58f6d49bcabf7bd1bc2e3d483" error_class=JSON::GeneratorError error="source sequence is illegal/malformed utf-8"
  2019-05-30 03:40:39 +0000 [warn]: #0 suppressed same stacktrace
#<Thread:0x00007f9c5099a450@/usr/local/bundle/gems/fluent-plugin-cloudwatch-logs-0.7.3/lib/fluent/plugin/out_cloudwatch_logs.rb:244 run> terminated with exception (report_on_exception is true):
/usr/local/lib/ruby/2.5.0/json/common.rb:224:in `generate': source sequence is illegal/malformed utf-8 (JSON::GeneratorError)
	from /usr/local/lib/ruby/2.5.0/json/common.rb:224:in `generate'
	from /usr/local/lib/ruby/2.5.0/json/common.rb:394:in `dump'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/json.rb:35:in `dump'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/json/builder.rb:14:in `to_json'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/json/handler.rb:30:in `build_body'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/json/handler.rb:23:in `build_request'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/json/handler.rb:10:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/plugins/user_agent.rb:13:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/plugins/endpoint_pattern.rb:28:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/plugins/endpoint_discovery.rb:78:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/seahorse/client/plugins/endpoint.rb:45:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/plugins/param_validator.rb:24:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/seahorse/client/plugins/response_target.rb:23:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/seahorse/client/request.rb:70:in `send_request'
	from /usr/local/bundle/gems/aws-sdk-cloudwatchlogs-1.20.0/lib/aws-sdk-cloudwatchlogs/client.rb:1671:in `put_log_events'
	from /usr/local/bundle/gems/fluent-plugin-cloudwatch-logs-0.7.3/lib/fluent/plugin/out_cloudwatch_logs.rb:329:in `put_events'
	from /usr/local/bundle/gems/fluent-plugin-cloudwatch-logs-0.7.3/lib/fluent/plugin/out_cloudwatch_logs.rb:309:in `put_events_by_chunk'
	from /usr/local/bundle/gems/fluent-plugin-cloudwatch-logs-0.7.3/lib/fluent/plugin/out_cloudwatch_logs.rb:247:in `block (2 levels) in write'
```
...

#### Steps to replicate

Currently 11GB of logs are queued up, and I can't tell which message is the culprit from the exception.  Assistance identifying the bad spooled message would be appreciated.

Config:

```
  <store>
    <buffer>
      @type file
      path /var/spool/log_relay
      flush_interval 5
    </buffer>

    @type cloudwatch_logs
    log_group_name [name]
    log_stream_name [name
    auto_create_stream true
    json_handler yajl
  </store>

#### Expected Behavior or What you need to ask

Plugin should not crash with a JSON encoding error.

#### Using Fluentd and CloudWatchLogs plugin versions

* Fluend gem 1.5.0 on Ruby:2.5.1 Docker container

```
fluent-gem list

*** LOCAL GEMS ***

```
aws-eventstream (1.0.3)
aws-partitions (1.169.0)
aws-sdk-cloudwatchlogs (1.20.0)
aws-sdk-core (3.54.0)
aws-sigv4 (1.1.0)
bigdecimal (default: 1.3.4)
bundler (1.16.6, default: 1.16.2)
cmath (default: 1.0.0)
cool.io (1.5.4)
csv (default: 1.0.0)
date (default: 1.0.0)
dbm (default: 1.0.0)
did_you_mean (1.2.0)
dig_rb (1.0.1)
etc (default: 1.0.0)
fcntl (default: 1.0.0)
fiddle (default: 1.0.0)
fileutils (default: 1.0.2)
fluent-plugin-cloudwatch-logs (0.7.3)
fluentd (1.5.0)
gdbm (default: 2.0.0)
http_parser.rb (0.6.0)
io-console (default: 0.4.6)
ipaddr (default: 1.2.0)
jmespath (1.4.0)
json (default: 2.1.0)
minitest (5.10.3)
msgpack (1.2.10)
net-telnet (0.1.1)
openssl (default: 2.1.0)
power_assert (1.1.1)
psych (default: 3.0.2)
rake (12.3.0)
rdoc (default: 6.0.1)
rubygems-update (2.7.7)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
serverengine (2.1.1)
sigdump (0.2.4)
stringio (default: 0.0.1)
strptime (0.2.3)
strscan (default: 1.0.0)
test-unit (3.2.7)
thread_safe (0.3.6)
tzinfo (1.2.5)
tzinfo-data (1.2019.1)
webrick (default: 1.4.2)
xmlrpc (0.3.0)
yajl-ruby (1.4.1)
zlib (default: 1.0.0)
```

```
2019-05-30 03:40:22 +0000 [info]: starting fluentd-1.5.0 pid=8 ruby="2.5.1"
2019-05-30 03:40:22 +0000 [info]: spawn command to main:  cmdline=["/usr/local/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/local/bundle/bin/fluentd", "--under-supervisor"]
2019-05-30 03:40:23 +0000 [info]: gem 'fluent-plugin-cloudwatch-logs' version '0.7.3'
2019-05-30 03:40:23 +0000 [info]: gem 'fluentd' version '1.5.0'
2019-05-30 03:40:23 +0000 [info]: adding match pattern="**" type="copy"
2019-05-30 03:40:23 +0000 [info]: adding source type="udp"
2019-05-30 03:40:23 +0000 [info]: adding source type="tcp"
2019-05-30 03:40:23 +0000 [info]: #0 starting fluentd worker pid=12 ppid=8 worker=0
2019-05-30 03:40:23 +0000 [info]: #0 listening udp socket bind="0.0.0.0" port=514
#<Thread:0x0000558c809d7620@/usr/local/bundle/gems/fluent-plugin-cloudwatch-logs-0.7.3/lib/fluent/plugin/out_cloudwatch_logs.rb:244 run> terminated with exception (report_on_exception is true):
2019-05-30 03:40:23 +0000 [info]: #0 fluentd worker is now running worker=0
/usr/local/lib/ruby/2.5.0/json/common.rb:224:in `generate': source sequence is illegal/malformed utf-8 (JSON::GeneratorError)
	from /usr/local/lib/ruby/2.5.0/json/common.rb:224:in `generate'
	from /usr/local/lib/ruby/2.5.0/json/common.rb:394:in `dump'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/json.rb:35:in `dump'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/json/builder.rb:14:in `to_json'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/json/handler.rb:30:in `build_body'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/json/handler.rb:23:in `build_request'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/json/handler.rb:10:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/plugins/user_agent.rb:13:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/plugins/endpoint_pattern.rb:28:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/plugins/endpoint_discovery.rb:78:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/seahorse/client/plugins/endpoint.rb:45:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/plugins/param_validator.rb:24:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/seahorse/client/plugins/response_target.rb:23:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/seahorse/client/request.rb:70:in `send_request'
	from /usr/local/bundle/gems/aws-sdk-cloudwatchlogs-1.20.0/lib/aws-sdk-cloudwatchlogs/client.rb:1671:in `put_log_events'
	from /usr/local/bundle/gems/fluent-plugin-cloudwatch-logs-0.7.3/lib/fluent/plugin/out_cloudwatch_logs.rb:329:in `put_events'
	from /usr/local/bundle/gems/fluent-plugin-cloudwatch-logs-0.7.3/lib/fluent/plugin/out_cloudwatch_logs.rb:309:in `put_events_by_chunk'
	from /usr/local/bundle/gems/fluent-plugin-cloudwatch-logs-0.7.3/lib/fluent/plugin/out_cloudwatch_logs.rb:247:in `block (2 levels) in write'
2019-05-30 03:40:24 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2019-05-30 03:40:25 +0000 chunk="589eb6c58f6d49bcabf7bd1bc2e3d483" error_class=JSON::GeneratorError error="source sequence is illegal/malformed utf-8"
  2019-05-30 03:40:24 +0000 [warn]: #0 /usr/local/lib/ruby/2.5.0/json/common.rb:224:in `generate'
  2019-05-30 03:40:24 +0000 [warn]: #0 /usr/local/lib/ruby/2.5.0/json/common.rb:224:in `generate'
  2019-05-30 03:40:24 +0000 [warn]: #0 /usr/local/lib/ruby/2.5.0/json/common.rb:394:in `dump'
  2019-05-30 03:40:24 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/json.rb:35:in `dump'
  2019-05-30 03:40:24 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/json/builder.rb:14:in `to_json'
  2019-05-30 03:40:24 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/json/handler.rb:30:in `build_body'
  2019-05-30 03:40:24 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/json/handler.rb:23:in `build_request'
  2019-05-30 03:40:24 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/json/handler.rb:10:in `call'
  2019-05-30 03:40:24 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/plugins/user_agent.rb:13:in `call'
  2019-05-30 03:40:24 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/plugins/endpoint_pattern.rb:28:in `call'
  2019-05-30 03:40:24 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/plugins/endpoint_discovery.rb:78:in `call'
  2019-05-30 03:40:24 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/seahorse/client/plugins/endpoint.rb:45:in `call'
  2019-05-30 03:40:24 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/plugins/param_validator.rb:24:in `call'
  2019-05-30 03:40:24 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
  2019-05-30 03:40:24 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
  2019-05-30 03:40:24 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
  2019-05-30 03:40:24 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
  2019-05-30 03:40:24 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
  2019-05-30 03:40:24 +0000 [warn]: #0 /#<Thread:0x0000558c80492520@/usr/local/bundle/gems/fluent-plugin-cloudwatch-logs-0.7.3/lib/fluent/plugin/out_cloudwatch_logs.rb:244 run> terminated with exception (report_on_exception is true):
usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/seahorse/client/plugins/response_target.rb:23:in `call'
/usr/local/lib/ruby/2.5.0/json/common.rb:224:in `generate': source sequence is illegal/malformed utf-8 (JSON::GeneratorError)
  2019-05-30 03:40:24 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/seahorse/client/request.rb:70:in `send_request'
  2019-05-30 03:40:24 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-cloudwatchlogs-1.20.0/lib/aws-sdk-cloudwatchlogs/client.rb:1671:in `put_log_events'
  2019-05-30 03:40:24 +0000 [warn]: #0 /usr/local/bundle/gems/fluent-plugin-cloudwatch-logs-0.7.3/lib/fluent/plugin/out_cloudwatch_logs.rb:329:in `put_events'
  2019-05-30 03:40:24 +0000 [warn]: #0 /usr/local/bundle/gems/fluent-plugin-cloudwatch-logs-0.7.3/lib/fluent/plugin/out_cloudwatch_logs.rb:309:in `put_events_by_chunk'
  2019-05-30 03:40:24 +0000 [warn]: #0 /usr/local/bundle/gems/fluent-plugin-cloudwatch-logs-0.7.3/lib/fluent/plugin/out_cloudwatch_logs.rb:247:in `block (2 levels) in write'
	from /usr/local/lib/ruby/2.5.0/json/common.rb:224:in `generate'
	from /usr/local/lib/ruby/2.5.0/json/common.rb:394:in `dump'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/json.rb:35:in `dump'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/json/builder.rb:14:in `to_json'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/json/handler.rb:30:in `build_body'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/json/handler.rb:23:in `build_request'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/json/handler.rb:10:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/plugins/user_agent.rb:13:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/plugins/endpoint_pattern.rb:28:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/plugins/endpoint_discovery.rb:78:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/seahorse/client/plugins/endpoint.rb:45:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/plugins/param_validator.rb:24:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/seahorse/client/plugins/response_target.rb:23:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.54.0/lib/seahorse/client/request.rb:70:in `send_request'
	from /usr/local/bundle/gems/aws-sdk-cloudwatchlogs-1.20.0/lib/aws-sdk-cloudwatchlogs/client.rb:1671:in `put_log_events'
	from /usr/local/bundle/gems/fluent-plugin-cloudwatch-logs-0.7.3/lib/fluent/plugin/out_cloudwatch_logs.rb:329:in `put_events'
	from /usr/local/bundle/gems/fluent-plugin-cloudwatch-logs-0.7.3/lib/fluent/plugin/out_cloudwatch_logs.rb:309:in `put_events_by_chunk'
	from /usr/local/bundle/gems/fluent-plugin-cloudwatch-logs-0.7.3/lib/fluent/plugin/out_cloudwatch_logs.rb:247:in `block (2 levels) in write'
```

Per https://github.com/fluent-plugins-nursery/fluent-plugin-cloudwatch-logs/issues/38 I tried enabling the Yajl encoder, but that had no effect.  

[EDIT: Formatting]

**Comment by RootTJNII** [comment]
Fluentd is forcing ASCII-8BIT in the supervisor: https://github.com/fluent/fluentd/blob/08a31d20c0f6158b2d804ea5bac131938d8c5551/lib/fluent/supervisor.rb#L605
