### ISSUE TITLE
JSON ParserError

### ISSUE THREAD

**Issue by NikitaGl** [fluent-plugins-nursery/fluent-plugin-cloudwatch-logs#156]
#### Problem

I'm continuously experiencing JSON parse exceptions, while trying to extract my application logs from CloudWatch. No matter what kind of logs are there, even simple one-liner like ``` Start application N``` could not be parsed. Using latest fluentd and cloudwatch-logs-plugin on Alpine in docker container.

#### Steps to replicate
Input config:
```
<source>
  @type cloudwatch_logs
  region eu-central-1
  tag clw.in
  log_group_name /ecs/fluentd-stage
  log_stream_name FLUENTD
  use_log_stream_name_prefix true
  state_file /tmp/clw.in.state
  use_aws_timestamp true
  # json_handler yajl
  json_handler json
</source>
...
```

Error log:
```
2019-07-22 13:18:24 +0000 [warn]: #0 thread exited by unexpected error plugin=Fluent::Plugin::CloudwatchLogsInput title=:in_cloudwatch_logs_runner error_class=JSON::ParserError error="785: unexpected token at '-07-20 19:16:44 +0000 [warn]: #0 got unrecoverable error in primary and no secondary error_class=Fluent::Plugin::ElasticsearchErrorHandler::ElasticsearchRequestAbortError error=\"Rejected Elasticsearch due to es_rejected_execution_exception\"'"
2019-07-22 13:18:24 +0000 [error]: #0 unexpected error error_class=JSON::ParserError error="785: unexpected token at '-07-20 19:16:44 +0000 [warn]: #0 got unrecoverable error in primary and no secondary error_class=Fluent::Plugin::ElasticsearchErrorHandler::ElasticsearchRequestAbortError error=\"Rejected Elasticsearch due to es_rejected_execution_exception\"'"
#<Thread:0x00005639fdd26788@/usr/lib/ruby/gems/2.5.0/gems/fluentd-1.6.2/lib/fluent/plugin_helper/thread.rb:70 run> terminated with exception (report_on_exception is true):
/usr/lib/ruby/gems/2.5.0/gems/json-2.2.0/lib/json/common.rb:156:in `parse': 785: unexpected token at '-07-20 19:16:44 +0000 [warn]: #0 got unrecoverable error in primary and no secondary error_class=Fluent::Plugin::ElasticsearchErrorHandler::ElasticsearchRequestAbortError error="Rejected Elasticsearch due to es_rejected_execution_exception"' (JSON::ParserError)
	from /usr/lib/ruby/gems/2.5.0/gems/json-2.2.0/lib/json/common.rb:156:in `parse'
	from /usr/lib/ruby/gems/2.5.0/gems/json-2.2.0/lib/json/common.rb:335:in `load'
	from /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-cloudwatch-logs-0.7.4/lib/fluent/plugin/in_cloudwatch_logs.rb:148:in `emit'
	from /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-cloudwatch-logs-0.7.4/lib/fluent/plugin/in_cloudwatch_logs.rb:120:in `block (2 levels) in run'
	from /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-cloudwatch-logs-0.7.4/lib/fluent/plugin/in_cloudwatch_logs.rb:119:in `each'
	from /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-cloudwatch-logs-0.7.4/lib/fluent/plugin/in_cloudwatch_logs.rb:119:in `block in run'
	from /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-cloudwatch-logs-0.7.4/lib/fluent/plugin/in_cloudwatch_logs.rb:116:in `each'
	from /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-cloudwatch-logs-0.7.4/lib/fluent/plugin/in_cloudwatch_logs.rb:116:in `run'
	from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.6.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
  2019-07-22 13:18:24 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/json-2.2.0/lib/json/common.rb:156:in `parse'
  2019-07-22 13:18:24 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/json-2.2.0/lib/json/common.rb:156:in `parse'
  2019-07-22 13:18:24 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/json-2.2.0/lib/json/common.rb:335:in `load'
  2019-07-22 13:18:24 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-cloudwatch-logs-0.7.4/lib/fluent/plugin/in_cloudwatch_logs.rb:148:in `emit'
  2019-07-22 13:18:24 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-cloudwatch-logs-0.7.4/lib/fluent/plugin/in_cloudwatch_logs.rb:120:in `block (2 levels) in run'
  2019-07-22 13:18:24 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-cloudwatch-logs-0.7.4/lib/fluent/plugin/in_cloudwatch_logs.rb:119:in `each'
  2019-07-22 13:18:24 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-cloudwatch-logs-0.7.4/lib/fluent/plugin/in_cloudwatch_logs.rb:119:in `block in run'
  2019-07-22 13:18:24 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-cloudwatch-logs-0.7.4/lib/fluent/plugin/in_cloudwatch_logs.rb:116:in `each'
  2019-07-22 13:18:24 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-cloudwatch-logs-0.7.4/lib/fluent/plugin/in_cloudwatch_logs.rb:116:in `run'
  2019-07-22 13:18:24 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.6.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
```

#### Expected Behavior or What you need to ask

I expect my CLW logs to be processed and moved to next step in fluentd pipeline.

#### Using Fluentd and CloudWatchLogs plugin versions

* Alpine 3.9.3
* Docker
* Fluentd v1.6.2
* json gem v2.2.0
* yajl gem v1.4.1
* Dependent gem versions loaded:
```
2019-07-22 13:06:23 +0000 [info]: fluent/log.rb:322:info: Worker 0 finished unexpectedly with status 1
2019-07-22 13:06:24 +0000 [info]: gem 'fluent-plugin-cloudwatch-logs' version '0.7.4'
2019-07-22 13:06:24 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '3.5.2'
2019-07-22 13:06:24 +0000 [info]: gem 'fluent-plugin-elb-log' version '1.0.1'
2019-07-22 13:06:24 +0000 [info]: gem 'fluent-plugin-geoip' version '1.3.1'
2019-07-22 13:06:24 +0000 [info]: gem 'fluent-plugin-rds-pgsql-log' version '0.5.0'
2019-07-22 13:06:24 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.2.0'
2019-07-22 13:06:24 +0000 [info]: gem 'fluentd' version '1.6.2'```

**Comment by rafaelmagu** [comment]
I'm seeing a similar issue with this plugin. No logs are being processed.

```
#<Thread:0x0000557d1b467150@/usr/lib/ruby/gems/2.5.0/gems/fluentd-1.6.2/lib/fluent/plugin_helper/thread.rb:70 run> terminated with exception (report_on_exception is true):
/usr/lib/ruby/gems/2.5.0/gems/yajl-ruby-1.4.1/lib/yajl.rb:44:in `parse': lexical error: invalid char in json text. (Yajl::ParseError)
                                       E0729 02:57:18.113567       1 r
                     (right here) ------^
	from /usr/lib/ruby/gems/2.5.0/gems/yajl-ruby-1.4.1/lib/yajl.rb:44:in `parse'
	from /usr/lib/ruby/gems/2.5.0/gems/yajl-ruby-1.4.1/lib/yajl.rb:18:in `load'
	from /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-cloudwatch-logs-0.7.4/lib/fluent/plugin/in_cloudwatch_logs.rb:148:in `emit'
	from /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-cloudwatch-logs-0.7.4/lib/fluent/plugin/in_cloudwatch_logs.rb:120:in `block (2 levels) in run'
	from /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-cloudwatch-logs-0.7.4/lib/fluent/plugin/in_cloudwatch_logs.rb:119:in `each'
	from /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-cloudwatch-logs-0.7.4/lib/fluent/plugin/in_cloudwatch_logs.rb:119:in `block in run'
	from /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-cloudwatch-logs-0.7.4/lib/fluent/plugin/in_cloudwatch_logs.rb:116:in `each'
	from /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-cloudwatch-logs-0.7.4/lib/fluent/plugin/in_cloudwatch_logs.rb:116:in `run'
	from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.6.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
```

Are there config examples of the ingestion feature running properly?

**Comment by rafaelmagu** [comment]
In fact, I don't understand why the plugin is even trying to parse JSON. This should be a flag.
