### ISSUE TITLE
source sequence is illegal/malformed utf-8

### ISSUE THREAD

**Issue by canburak** [fluent-plugins-nursery/fluent-plugin-cloudwatch-logs#38]
Hello,

This seems to block all the buffered messages:

```
2016-03-15 16:46:50 +0200 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-15 16:46:50 +0200 error_class="JSON::GeneratorError" error="source sequence is illegal/malformed utf-8" plugin_id="object:3f8add0ea248"
  2016-03-15 16:46:50 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-cloudwatch-logs-0.2.2/lib/fluent/plugin/out_cloudwatch_logs.rb:127:in `to_json'
  2016-03-15 16:46:50 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-cloudwatch-logs-0.2.2/lib/fluent/plugin/out_cloudwatch_logs.rb:127:in `block (2 levels) in write'
  2016-03-15 16:46:50 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-cloudwatch-logs-0.2.2/lib/fluent/plugin/out_cloudwatch_logs.rb:121:in `each'
  2016-03-15 16:46:50 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-cloudwatch-logs-0.2.2/lib/fluent/plugin/out_cloudwatch_logs.rb:121:in `block in write'
  2016-03-15 16:46:50 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-cloudwatch-logs-0.2.2/lib/fluent/plugin/out_cloudwatch_logs.rb:100:in `<<'
  2016-03-15 16:46:50 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-cloudwatch-logs-0.2.2/lib/fluent/plugin/out_cloudwatch_logs.rb:100:in `each'
  2016-03-15 16:46:50 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-cloudwatch-logs-0.2.2/lib/fluent/plugin/out_cloudwatch_logs.rb:100:in `each'
  2016-03-15 16:46:50 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-cloudwatch-logs-0.2.2/lib/fluent/plugin/out_cloudwatch_logs.rb:100:in `write'
  2016-03-15 16:46:50 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/buffer.rb:345:in `write_chunk'
  2016-03-15 16:46:50 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/buffer.rb:324:in `pop'
  2016-03-15 16:46:50 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/output.rb:321:in `try_flush'
  2016-03-15 16:46:50 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/output.rb:140:in `run'
```

**Comment by canburak** [comment]
Can I get a pointer to follow as these messages are stuck in the queue and I cannot further process them.

**Comment by jdrydn** [comment]
I've just switched to this plugin and I'm experiencing this too. Guessing this is still an issue?

**Comment by cosmo0920** [comment]
We use Yajl by default.
I guess this issue should not be occurred.
