### ISSUE TITLE
Encoding::UndefinedConversionError during buffer flush

### ISSUE THREAD

**Issue by againer** [fluent-plugins-nursery/fluent-plugin-cloudwatch-logs#65]
Getting `UndefinedConversionError error="\"\\xCC\" from ASCII-8BIT to UTF-8"`.   

ruby: 2.3.0
fluentd: 0.14.12
fluent-plugin-cloudwatch-logs: 0.3.6

Here is my config.
```
<source>
  @type tail
  path /opt/apps/cloudapp/current/log/production.log
  pos_file /opt/apps/fluent/log/production.log.pos
  format /^(?<all>.*)$/
  tag app.log
</source>

<match app.log>
  @type cloudwatch_logs
  log_group_name ...
  use_tag_as_stream true
  auto_create_stream true
  region us-east-1
  aws_key_id ...
  aws_sec_key ...
</match>

```

```
2017-02-12 20:23:24 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2017-02-12 20:23:25 +0000 chunk="5485b1a267dd67776c4d1d9dd06544ae" error_class=Encoding::UndefinedConversionError error="\"\\xCC\" from ASCII-8BIT to UTF-8"
  2017-02-12 20:23:24 +0000 [warn]: #0 /home/ubuntu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fluent-plugin-cloudwatch-logs-0.3.6/lib/fluent/plugin/out_cloudwatch_logs.rb:145:in `encode'
  2017-02-12 20:23:24 +0000 [warn]: #0 /home/ubuntu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fluent-plugin-cloudwatch-logs-0.3.6/lib/fluent/plugin/out_cloudwatch_logs.rb:145:in `to_json'
  2017-02-12 20:23:24 +0000 [warn]: #0 /home/ubuntu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fluent-plugin-cloudwatch-logs-0.3.6/lib/fluent/plugin/out_cloudwatch_logs.rb:145:in `block (2 levels) in write'
  2017-02-12 20:23:24 +0000 [warn]: #0 /home/ubuntu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fluent-plugin-cloudwatch-logs-0.3.6/lib/fluent/plugin/out_cloudwatch_logs.rb:138:in `each'
  2017-02-12 20:23:24 +0000 [warn]: #0 /home/ubuntu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fluent-plugin-cloudwatch-logs-0.3.6/lib/fluent/plugin/out_cloudwatch_logs.rb:138:in `block in write'
  2017-02-12 20:23:24 +0000 [warn]: #0 /home/ubuntu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fluent-plugin-cloudwatch-logs-0.3.6/lib/fluent/plugin/out_cloudwatch_logs.rb:111:in `each'
  2017-02-12 20:23:24 +0000 [warn]: #0 /home/ubuntu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fluent-plugin-cloudwatch-logs-0.3.6/lib/fluent/plugin/out_cloudwatch_logs.rb:111:in `write'
  2017-02-12 20:23:24 +0000 [warn]: #0 /home/ubuntu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fluentd-0.14.12/lib/fluent/compat/output.rb:128:in `write'
  2017-02-12 20:23:24 +0000 [warn]: #0 /home/ubuntu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fluentd-0.14.12/lib/fluent/plugin/output.rb:1018:in `try_flush'
  2017-02-12 20:23:24 +0000 [warn]: #0 /home/ubuntu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fluentd-0.14.12/lib/fluent/plugin/output.rb:1243:in `flush_thread_run'
  2017-02-12 20:23:24 +0000 [warn]: #0 /home/ubuntu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fluentd-0.14.12/lib/fluent/plugin/output.rb:401:in `block (2 levels) in start'
  2017-02-12 20:23:24 +0000 [warn]: #0 /home/ubuntu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fluentd-0.14.12/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
```

**Comment by againer** [comment]
https://github.com/ryotarai/fluent-plugin-cloudwatch-logs/blob/master/lib/fluent/plugin/out_cloudwatch_logs.rb#L145

**Comment by repeatedly** [comment]
https://github.com/ryotarai/fluent-plugin-cloudwatch-logs/pull/58 should fix this problem but I'm not sure why this PR is not merged yet...

**Comment by sampointer** [comment]
In https://github.com/sampointer/fluent-plugin-cloudwatch-ingest I took the approach of using `multi_json` so that whatever native or otherwise parser was bundled with fluentd would be used, for consistency.

**Comment by alterx** [comment]
Guys, I think I found the underlying problem, please refer to this issue
https://github.com/fluent/fluentd-kubernetes-daemonset/issues/13#issuecomment-318498707

**Comment by jpke** [comment]
Ran into this same problem and fixed it by updating gem dependencies in fluentd-cloudwatch image, and also adding
```
  <filter kubernetes.**>
    @type kubernetes_metadata
    @id filter_kube_metadata
    char_encoding utf-8
  </filter>

  <match **>
    @type cloudwatch_logs
    log_group_name "#{ENV['LOG_GROUP_NAME']}"
    auto_create_stream true
    use_tag_as_stream true
    json_handler yajl
  </match>
```

outlined in: https://github.com/fluent/fluentd-kubernetes-daemonset/pull/117

**Comment by cosmo0920** [comment]
We use Yajl by default and another solution is shown in https://github.com/fluent-plugins-nursery/fluent-plugin-cloudwatch-logs/issues/65#issuecomment-385096593.
