### ISSUE TITLE
unexpected error error="No such file or directory - addr"

### ISSUE THREAD

**Issue by valichek** [fluent-plugins-nursery/fluent-plugin-cloudwatch-logs#75]
Getting error when running Fluentd Daemonset for Kubernetes `v0.12-debian-cloudwatch` in minikube
[(v0.12/debian-cloudwatch/Dockerfile)](https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/docker-image/v0.12/debian-cloudwatch/Dockerfile)
Looks very similar to this issue https://github.com/tagomoris/fluent-plugin-secure-forward/issues/38

```
    <match **>
      # Plugin specific settings
      type cloudwatch_logs
      log_group_name minikube
      use_tag_as_stream true
      auto_create_stream true

      # Buffer settings
      buffer_chunk_limit 2M
      buffer_queue_limit 32
      flush_interval 10s
      max_retry_wait 30
      disable_retry_limit
      num_threads 8
    </match>
```

```
2017-08-23 16:22:18 +0000 [info]: adding match pattern="**" type="cloudwatch_logs"
2017-08-23 16:22:19 +0000 [error]: unexpected error error="No such file or directory - addr" 
2017-08-23 16:22:19 +0000 [error]: /var/lib/gems/2.3.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:587:in `ifconfig'
  2017-08-23 16:22:19 +0000 [error]: /var/lib/gems/2.3.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:634:in `mac_address'
  2017-08-23 16:22:19 +0000 [error]: /var/lib/gems/2.3.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:242:in `block in timestamp_create'
  2017-08-23 16:22:19 +0000 [error]: /var/lib/gems/2.3.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:232:in `synchronize'
  2017-08-23 16:22:19 +0000 [error]: /var/lib/gems/2.3.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:232:in `timestamp_create'
  2017-08-23 16:22:19 +0000 [error]: /var/lib/gems/2.3.0/gems/fluent-mixin-config-placeholders-0.4.0/lib/fluent/mixin/config_placeholders.rb:37:in `uuid_timestamp'
  2017-08-23 16:22:19 +0000 [error]: /var/lib/gems/2.3.0/gems/fluent-mixin-config-placeholders-0.4.0/lib/fluent/mixin/config_placeholders.rb:80:in `block (2 levels) in configure'
  2017-08-23 16:22:19 +0000 [error]: /var/lib/gems/2.3.0/gems/fluent-mixin-config-placeholders-0.4.0/lib/fluent/mixin/config_placeholders.rb:41:in `block in replace'
  2017-08-23 16:22:19 +0000 [error]: /var/lib/gems/2.3.0/gems/fluent-mixin-config-placeholders-0.4.0/lib/fluent/mixin/config_placeholders.rb:41:in `each'
  2017-08-23 16:22:19 +0000 [error]: /var/lib/gems/2.3.0/gems/fluent-mixin-config-placeholders-0.4.0/lib/fluent/mixin/config_placeholders.rb:41:in `reduce'
  2017-08-23 16:22:19 +0000 [error]: /var/lib/gems/2.3.0/gems/fluent-mixin-config-placeholders-0.4.0/lib/fluent/mixin/config_placeholders.rb:41:in `replace'
  2017-08-23 16:22:19 +0000 [error]: /var/lib/gems/2.3.0/gems/fluent-mixin-config-placeholders-0.4.0/lib/fluent/mixin/config_placeholders.rb:96:in `block in configure'
  2017-08-23 16:22:19 +0000 [error]: /var/lib/gems/2.3.0/gems/fluent-mixin-config-placeholders-0.4.0/lib/fluent/mixin/config_placeholders.rb:105:in `configure'
  2017-08-23 16:22:19 +0000 [error]: /var/lib/gems/2.3.0/gems/fluent-plugin-cloudwatch-logs-0.3.3/lib/fluent/plugin/out_cloudwatch_logs.rb:49:in `configure'
  2017-08-23 16:22:19 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/agent.rb:133:in `add_match'
  2017-08-23 16:22:19 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/agent.rb:64:in `block in configure'
  2017-08-23 16:22:19 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/agent.rb:57:in `each'
  2017-08-23 16:22:19 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/agent.rb:57:in `configure'
  2017-08-23 16:22:19 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/root_agent.rb:86:in `configure'
  2017-08-23 16:22:19 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/engine.rb:129:in `configure'
  2017-08-23 16:22:19 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/engine.rb:103:in `run_configure'
  2017-08-23 16:22:19 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/supervisor.rb:489:in `run_configure'
  2017-08-23 16:22:19 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/supervisor.rb:160:in `block in start'
  2017-08-23 16:22:19 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/supervisor.rb:366:in `main_process'
  2017-08-23 16:22:19 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/supervisor.rb:339:in `block in supervise'
  2017-08-23 16:22:19 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/supervisor.rb:338:in `fork'
  2017-08-23 16:22:19 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/supervisor.rb:338:in `supervise'
  2017-08-23 16:22:19 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/supervisor.rb:156:in `start'
  2017-08-23 16:22:19 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
  2017-08-23 16:22:19 +0000 [error]: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2017-08-23 16:22:19 +0000 [error]: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2017-08-23 16:22:19 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-0.12.39/bin/fluentd:5:in `<top (required)>'
  2017-08-23 16:22:19 +0000 [error]: /usr/local/bin/fluentd:22:in `load'
  2017-08-23 16:22:19 +0000 [error]: /usr/local/bin/fluentd:22:in `<main>' 
```

**Comment by childofb0d0m** [comment]
Hello

I have the same issue. Did you find a way to solve it ?
Thanks

**Comment by danielfm** [comment]
I managed to fix the issue on my side.

The problem was that my Docker base image (`debian:stretch-slim`) didn't have the `ifconfig` binary installed, so installing the `net-tools` package via `apt-get` fixed the problem.

**Comment by valichek** [comment]
@danielfm nice job, my hero

**Comment by cosmo0920** [comment]
Looks resolved. Closing.
