### ISSUE TITLE
feature request: tag placeholder

### ISSUE THREAD

**Issue by koooge** [fluent-plugins-nursery/fluent-plugin-cloudwatch-logs#93]
Hi! I want to use placeholder like below, but this plugin does not support placeholder yet, right?

```
<match *.**>
@type copy
  <store>
    type cloudwatch_logs
     log_group_name log-group-${tag[1]}
     log_stream_name log-stream-${tag[2]}
...
```

cf. https://github.com/fluent/fluentd/blob/1b9cddd03c271f06abbc32d9f8fe93c1d496f654/lib/fluent/plugin/output.rb#L687

**Comment by repeatedly** [comment]
We can support this feature after merged https://github.com/ryotarai/fluent-plugin-cloudwatch-logs/pull/71

**Comment by koooge** [comment]
yes! hopefully merge #71 🙏

**Comment by koooge** [comment]
Hi. I'm glad to upgrade fluentd to v0.14 :tada:

fluent-plugin-cloudwatch-logs did not seem to care tag placeholders. 😢 

```
2018-04-27 02:18:29 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-04-27 02:18:30 +0000 chunk="56acb1b1c285caf0f9a635814dd15292" error_class=Aws::CloudWatchLogs::Errors::InvalidParameterException error="1 validation error detected: Value 'log-group-${tag[1]}' at 'logGroupName' failed to satisfy constraint: Member must satisfy regular expression pattern: [\\.\\-_/#A-Za-z0-9]+"
  2018-04-27 02:18:29 +0000 [warn]: #0 /usr/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.20.2/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
  2018-04-27 02:18:29 +0000 [warn]: #0 /usr/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.20.2/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
  2018-04-27 02:18:29 +0000 [warn]: #0 /usr/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.20.2/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
  2018-04-27 02:18:29 +0000 [warn]: #0 /usr/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.20.2/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
  2018-04-27 02:18:29 +0000 [warn]: #0 /usr/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.20.2/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
  2018-04-27 02:18:29 +0000 [warn]: #0 /usr/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.20.2/lib/seahorse/client/plugins/response_target.rb:23:in `call'
  2018-04-27 02:18:29 +0000 [warn]: #0 /usr/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.20.2/lib/seahorse/client/request.rb:70:in `send_request'
  2018-04-27 02:18:29 +0000 [warn]: #0 /usr/lib/ruby/gems/2.4.0/gems/aws-sdk-cloudwatchlogs-1.3.0/lib/aws-sdk-cloudwatchlogs/client.rb:359:in `create_log_group'
  2018-04-27 02:18:29 +0000 [warn]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluent-plugin-cloudwatch-logs-0.5.0/lib/fluent/plugin/out_cloudwatch_logs.rb:385:in `create_log_group'
  2018-04-27 02:18:29 +0000 [warn]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluent-plugin-cloudwatch-logs-0.5.0/lib/fluent/plugin/out_cloudwatch_logs.rb:193:in `block in write'
  2018-04-27 02:18:29 +0000 [warn]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluent-plugin-cloudwatch-logs-0.5.0/lib/fluent/plugin/out_cloudwatch_logs.rb:160:in `each'
  2018-04-27 02:18:29 +0000 [warn]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluent-plugin-cloudwatch-logs-0.5.0/lib/fluent/plugin/out_cloudwatch_logs.rb:160:in `write'
  2018-04-27 02:18:29 +0000 [warn]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.1.3/lib/fluent/plugin/output.rb:1096:in `try_flush'
  2018-04-27 02:18:29 +0000 [warn]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.1.3/lib/fluent/plugin/output.rb:1329:in `flush_thread_run'
  2018-04-27 02:18:29 +0000 [warn]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.1.3/lib/fluent/plugin/output.rb:439:in `block (2 levels) in start'
  2018-04-27 02:18:29 +0000 [warn]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.1.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
```
